### ISSUE TITLE
[Bug]: getMenuNameAttribute is not working in model. 

### ISSUE THREAD

**Issue by shanijahania** [Biostate/filament-menu-builder#1]
### What happened?

First of all I would like to thank you for the brilliant work. 

I am trying to create the menu through model. I have setup the model as per your instructions but the method getMenuNameAttribute is not passing the attribute name correctly. for example the attribute name is "title" in my case but its still looking for "name" attribute. 

Below is my code sample

`public function getMenuNameAttribute(): string
    {
        return $this->title;
    }`
 

### How to reproduce the bug

When pass any attribute other then title I get this error.

### Package Version

latest

### PHP Version

8,3

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by Biostate** [comment]
You can check this on v1.0.6.
